### ISSUE TITLE
Recursive definitions

### ISSUE THREAD

**Issue by sirzooro** [skvadrik/re2c#146]
I need to implement recursive rule like this:
```
WORDS = [a-zA-Z ]+;
DATA = "(" (WORDS | DATA)* ")";

DATA {...}
```

I tried to write this as above, but re2c reports error. There is a workaround for this -  can simplify this as below, and validate brackets elsewhere (e.g. in parser):
```
DATA = "(" [a-zA-Z() ]+ ")";
DATA {...}
```

Could you add support for something like this?

BTW, you could use `\0` to reference self, like below. This is similar to backreferences used in some regexp engines:
```
DATA = "(" (WORDS | \0)* ")";
```

**Comment by skvadrik** [comment]
In short, what you're asking about exceeds the power of regular expressions (as a mathematical formalism). Regular expression by definition is:

- empty string
- single alphabet letter
- alternative `r1 | r2` where `r1` and `r2` are regular expressions
- concatenation `r1 r2` where `r1` and `r2` are regular expressions
- iteration  `r*` where `r` is a regular expression

Put in a slightly different way, regular grammar (a formalism equal to regular expression) can only have productions of the form:

- `A ---> a`
- `A ---> Aa`

(The second rule `A ---> Aa` corresponds to left-regular grammars, right regular grammars would have `A ---> aA`, but not two at the same time).

What you want is production of the form `A -> xAy`, which describes nested structures. For that you will need at least context-free grammar (and a computationally more complex parsing algorithm).

Backreferences are even more complicated (they don't even fall into context-free grammars). Engines that allow rewbrs (regular expressions with backreferences) must use recursive backtracking algorithm (with exponential complexity) rather than finite automata (with linear complexity).

You might want to read http://www.dickgrune.com/Books/PTAPG_2nd_Edition/.

It's highly unlikely that re2c will ever have backreferences or nested structures.

**Comment by skvadrik** [comment]
Or read this: https://swtch.com/~rsc/regexp/regexp1.html and subsequent articles, if you want to know how backreferences are handled in google's RE2 engine. A spoiler: when RE2 finds backreference, it falls back to recursive backtracking (and so does grep and other real-world engines).
