### ISSUE TITLE
Please add support for ABNF syntax (RFC 5234)

### ISSUE THREAD

**Issue by sirzooro** [skvadrik/re2c#150]
Translation of formal protocol syntax from ABNF notation used in RFC documents to re2c format is quite tedious: copy, paste, reorder rules, modify syntax, rinse and repeat. This may also introduce bugs if typo will be made somewhere. So adding ABNF syntax to re2c would be beneficial. I propose to do it in following way:
- current and ABNF syntaxes probably could not be supported together, so new option `--abnf` would be needed to select this syntax;
- `--case-inverted` should be enabled automatically;
- some syntax changes probably would be needed: use semicolon at end of definition, use `//` for comments instead of `;`

Edit: please also support syntax from RFC 7405 - Case-Sensitive String Support in ABNF.

**Comment by skvadrik** [comment]
Could you add links to:

- ABNF  specification
- an example of RFC you're trying to convert

**Comment by skvadrik** [comment]
Also, BNF notation allows to describe context-free grammars, while re2c deals with regular grammars. In order to use BNF syntax with re2c we would have to use (invent?) some BNF flavour restricted to regular grammars.

**Comment by skvadrik** [comment]
Converting from RFC's ABNF to this regular-BNF notation would probably be as bad as converting from ABNF to normal re2c syntax.

Ideally re2c should do the grammar rewriting for you. While this rewriting is an interesting project, it's not so simple. And since re2c will end up rejecting many grammars (because they are not regular), it's better to make a context-free fellow engine (lalr2c or so, I even have a prototype of that: https://github.com/skvadrik/lalr2c).

**Comment by sirzooro** [comment]
I am working on https://www.ietf.org/rfc/rfc3261.txt now.

Regular grammars are subset of context-free grammars, so you should be able to implement syntax covering this subset only. This will be enough to translate most basic rules which specify how to build headers, etc. Other things I will have to extract anyway, so I will need to do some context switching in re2c or use external parser like bison anyway.

**Comment by skvadrik** [comment]
If I get it right, what you want is simple syntactic transformation from ABNF to re2c. Say, the following ABNF
```
x =/ "(" x ")" 
y =/ y ")"
z =/ "(" z
```
should be transformed to
```
x = "" | "(" x ")";
y = "" | y ")";
z = "" | "(" z;
```
This transformation is straightforward (in fact, it's much easier to write a simple preprocessor that will do the job than make re2c support yet another sub-syntax). 

However, this transformation is not very helpful: in the example above re2c will reject all three rules for `x`, `y` and `z` because they all are recursive. While in reality it's only the `x` rule which is non-regular and should be rejected, but both rules for `y` and `z` are perfectly regular:
```
y = ")"*;
z = "("*;
```

**Comment by sirzooro** [comment]
Yes, but this should be for rx-like expressions only. In particular I do not need the `=/` operator. I want to automatically translate rules like this:
```
AAA = %d13.10 \x10-20 "test"
BBB = *AAA 1*AAA 2AAA 1*4AAA [AAA]
CCC = (AAA / BBB) *<AAA>
```
to this:
```
AAA = "\x0D\x0A" [\x10-\x20] 'test';
BBB = AAA* AAA{1,} AAA{2} AAA{1,4} AAA?;
CCC = (AAA | BBB) AAA*;
```
I would like to copy rules like this from RFC docs and avoid this extra manual syntax conversion step which is needed now.

**Comment by skvadrik** [comment]
I agree that conversion should be done automatically.

But adding ABNF syntax to re2c is not a good idea for the following reasons:

- ABNF is for context-free grammars, it would confuse re2c users (they might think that re2c supports full class of grammars described by ABNF)
- this conversion step  is an independent transformation, so it should be done by an independent preprocessor/plugin
- this approach doesn't scale: re2c parser would quickly become unmaintainable

The solution: one can create a standalone converter (a small script `abnf2re` or something). Or reuse some already existing program like abnf2c: https://sourceforge.net/projects/abnf2c/.

By the way, re2c has partial support for flex syntax (`-F` flag). This flex sub-syntax  is one of the primary reasons I'm strongly against adding ABNF sub-syntax: it creates more problems than it solves. Very few re2c programs use it, and it's much easier to convert these programs than maintain flex sub-syntax in re2c.

**Comment by sirzooro** [comment]
OK, I see. Standalone tool is also good for me.
And regarding potential confusion - every time you would mention ABNF support, there should be also note that it is only partial support, with optional link to page describing what is supported and what not.

**Comment by trofi** [comment]
Let's close it as ABNF is a bit far from re2c's scope. We'll unlikely work on it as part of re2c project.
