### ISSUE TITLE
Reading files with "rb" causes issues in Windows

### ISSUE THREAD

**Issue by pauloscustodio** [skvadrik/re2c#162]
In input.cc:18 the .re file is opened in binary mode - fopen (file_name.c_str (), "rb");
This causes a test failures on a git clone of the repository on Windows:

- code_points_error_esc.re:
  re2c: warning: line 2: column 5: escape has no effect: '\' [-Wuseless-escape]

because the back-slash is followed by a '\r' and then a '\n'

- code_points_error_lf.re
  re2c: error: line 2, column 7: syntax error

column number is 6 is the reference file, result is 7 due to extra '\r'

In git, when a repository is cloned in Windows, all text files get '\r\n' line endings, which are then converted to '\n' on commit. By opening in binary mode in input.cc, the '\r' are not filtered by stdio.

**Comment by skvadrik** [comment]
I think the issue is not in `"rb"` mode, rather in handling of newlines. re2c should handle all kinds of newlines, and it does for the most part, but in some places newlines are unexpected.

Please see the fix: https://github.com/skvadrik/re2c/commit/54b50c0bbfe4a865bf004ef51fb639156a7657d7,
does it work for you?

**Comment by pauloscustodio** [comment]
Yes, 54b50c0
<https://github.com/skvadrik/re2c/commit/54b50c0bbfe4a865bf004ef51fb639156a7657d7>
solves
the issue I reported.

Thanks.
