### ISSUE TITLE
Wikipedia's article on re2c

### ISSUE THREAD

**Issue by ruimaciel** [skvadrik/re2c#168]
I've noticed that wikipedia didn't hosted an article on re2c.
Consequenty, I've started one.

Here's a link to wikipedia's article on re2c:

https://en.wikipedia.org/wiki/Re2c

If anyone is willing to contribute anything to the article, go for it.

**Comment by skvadrik** [comment]
Great! Only I believe it should be either "re2c" or "RE2C", not "Re2c" :)

**Comment by ddalek** [comment]
I'm afraid it's not possible to have a Wikipedia article address slug starting with a small character (see iPhone article for example). And since it's pretty universally referred to as re2c (with the original paper being the sole exception I've seen) I feel it should be re2c (all small) in the title as it is. Do you agree? :) Also per Wikipedia policies caps in titles typically indicate abbreviations and I was unable to find any name re2c unrolls to.

**Comment by skvadrik** [comment]
"re2c" is fine by me, "Re2c" is not.
The name itself is an abbreviation from "Regular Expressions to C (programming language)".
The problem with small letters is that you cannot start a sentence with "re2c" without violating either the name or the norms of written English. That's why the paper uses "RE2C" I think.

**Comment by ddalek** [comment]
But re2c _is_ referred to as re2c in Wikipedia article (including its title). :) The URL slug is a deficiency of MediaWiki engine. That's why musl[1], vbcc[2] or previously mentioned iPhone have to deal with the imperfect URLs.

[1] https://en.wikipedia.org/wiki/Musl
[2] https://en.wikipedia.org/wiki/Vbcc

**Comment by skvadrik** [comment]
Yes, @ruimaciel titled the artiicle "Re2c" at first, but then fixed it to "re2c".  My message was written before the fix.

**Comment by ddalek** [comment]
Cool. :) I've added some citations so it's not marked for deletion due to lack of proper sourcing.

**Comment by ruimaciel** [comment]
It seems that wikipedia's article on re2c has been flagged due to issues such as "may rely excessively on sources too closely associated with the subject".  Is anyone able to contribute a third-party source on the merits of re2c?

**Comment by skvadrik** [comment]
Well, first, the original paper: http://dl.acm.org/citation.cfm?doid=176454.176487
Then all the projects and distributions that use it (some are listed  on our website) http://re2c.org/

How do you communicate with moderators?

**Comment by ruimaciel** [comment]
Unfortunately the original paper and data from the project's website are considered as sources too closely associated with the subject.

I assume that whoever flagged the article already looked into those sources, and found them insufficient.

Are there any 3rd party sources that reference re2c in a meaningful manner?

**Comment by skvadrik** [comment]
Ninja home page references re2c as one of its build dependencies: http://clausklein.github.io/ninja/#id47
Since ninja itself is used in a plenty of projects (including other build systems such as cmake and meson), re2c is a transitive build dependency of lots of software. :)

PHP also mentions re2c as one of its build dependencies: http://www.phpinternalsbook.com/build_system/building_php.html#obtaining-the-source-code

**Comment by ruimaciel** [comment]
I've added those sources and removed the warning from the article.  Let's see if those third-party sources are enough.

**Comment by skvadrik** [comment]
I hope so, thank you!
