### ISSUE TITLE
Bugs with option: re2c:flags:no-debug-info

### ISSUE THREAD

**Issue by Durimar** [skvadrik/re2c#201]
Hello,
i test re2c with simple file test.re:
//---------------------------
/*!re2c
    re2c:flags:no-debug-info = 1;
*/
int get_token(const char *cur)
{
   return 0;
}
//--------------------

and found that:

1.
re2c always generate debug #line1 (with no-debug-info = 1 and with no-debug-info = 0):
#line 1 "D:\Proj\ConsoleApp1\test.re"

2. 
Visual Studio 2017 generate warning
1>d:\proj\consoleapp1\test.cpp(2): warning C4129: 'P': unrecognized character escape sequence
1>d:\proj\consoleapp1\test.cpp(2): warning C4129: 'C': unrecognized character escape sequence

I think all '\' symbols must be escaped like this:
#line 1 "D:\\Proj\\ConsoleApp1\\test.re"

Thanks.

**Comment by skvadrik** [comment]
Both issues confirmed, thanks for reporting.

I pushed the fix for backslash escapes: https://github.com/skvadrik/re2c/commit/4a614d60075eafbdcedf1707c886591a57f32982.

I might have a look at line info issue tomorrow, it's not that difficult. A long time ago re2c used to make one pass over the input and write output straight away, and in some places that one-pass approach still remains. In particular, the first line info is generated before re2c even reads the configuration.

**Comment by skvadrik** [comment]
Pushed the fix for `#line` directives: https://github.com/skvadrik/re2c/commit/fe4bf2e3857fd29b8d00264a2540366db57da4d6.
