### ISSUE TITLE
re2c option -F (flex syntax) broken

### ISSUE THREAD

**Issue by genivia-inc** [skvadrik/re2c#229]
re2x -F (Flex syntax) version 1.1.1 throws a syntax error for the regex `(a|ab)ba` but the regex `(a|ab)(ba)` works fine for some reason. This is valid Flex syntax.

I can work around this issue for now by using regex `("a"|"ab")"ba"`, but it would be nice if re2c accepts Flex syntax.

**Comment by skvadrik** [comment]
This does look like an error to me. But this behaviour goes back as far as re2c-0.13.6 (and supposedly before that), and Flex syntax has always been only vaguely defined in re2c. I first need to understand what re2c already supports (otherwise the fix may break someone else's code), and then see how we can fix that without introducing ambiguity in grammar.

There is another workaround. This causes syntax error:
```
/*!re2c
    (a|ab)ba {}
*/
```
But this doesn't (indentation doesn't matter as long as the code in braces is on a new line):
```
/*!re2c
    (a|ab)ba
    {}
*/
```

**Comment by genivia-inc** [comment]
Thanks for the suggestion. With the `{ }` code block on the same line it is strange that any character after a `)`, `]`, `*` or `+` in the regex causes this failure, e.g. `(a)b` and `[a]b` and `a*b` and `a+b` fail.

**Comment by skvadrik** [comment]
@genivia-inc It's not the special characters `)`, `]`, `*`, `+` that cause the error, it's the raw character at the end of the regexp followed by one or more spaces and the opening brace `{`. This simple example also fails:
```
/*!re2c
    a {}
*/
```
The reason why it fails is partly historical: partial support for flex syntax was added on top of already existing re2c-specific syntax, which caused parsing conflicts (some due to limitations in the implementation, some due to genuine ambiguity in grammar).

I have a fix for the original example, but I want to make sure that it doesn't break existing code and check similar cases.

**Comment by skvadrik** [comment]
@genivia-inc This should fix your example (and a couple of other cases in `-F` mode): https://github.com/skvadrik/re2c/commit/30a0682c036d07dd6ff5b92d5893a348cc7b777a
