### ISSUE TITLE
Overlapping expressions

### ISSUE THREAD

**Issue by kakaraky** [skvadrik/re2c#303]
Consider the following re:
([^\x00]{16}"\n\x00\x00") | ([Bb][Ii][Gg])

Re2c generates something that starts with:
	u8 yych;
	if ((YYLIMIT - YYCURSOR) < 19) return 0;(19);
	yych = *YYCURSOR;
	switch (yych) {
	case 0x00:	goto yy2;
	case 'B':
	case 'b':	goto yy4;
	default:	goto yy3;
	}
yy2:
	YYCURSOR = YYMARKER;
	goto yy9;
[...]
Which means if the first u8 is 0 it matched, which is wrong. Ultimately the generated code goes into an infinite loop, which by removing either expression to either side of "|" seems to work correctly.

**Comment by skvadrik** [comment]
Hi, the code posted above is ill-formed and incomplete. From it I can only tell that your .re file is broken, but I cannot tell exactly how and what are the steps to correct it. Please do the following:

- post the complete .re file
- either attach the file (by clicking the button _"Attach files by dragging & dropping, selecting or pasting them"_ at the bottom of the comment edit box) or use Markdown in your comments to separate code from text (see [Markdown cheatsheet](https://github.com/adam-p/markdown-here/wiki/Markdown-Cheatsheet#code))
- post the full command which you use to run re2c and the example

Regarding your concern that `case 0x00: goto yy2;` matches `\x00`, this is ok because `yy2` is the _default rule_, which captures all the patterns that are not covered by normal rules. Infinite loop could be caused by not handling default case properly.

Finally, here is an example that that uses your regexp and works fine. Compile and run as `re2c example.re -oexample.c && cc example.c -oexample && ./example`. As you can see in the generated example.c, it starts with approximately the same code as you posted above.
```c
#include <assert.h>

static int lex(const char *YYCURSOR)
{
    const char *YYMARKER;
    /*!re2c

    re2c:define:YYCTYPE = char;
    re2c:yyfill:enable = 0;

    ([^\x00]{16}"\n\x00\x00") | ([Bb][Ii][Gg]) { return 0; }
    *                                          { return -1; }

    */
}

int main()
{
    assert(lex("big") == 0);
    assert(lex("aaaaAAAAaaaaAAAA\n\000\000") == 0);
    return 0;
}
```

**Comment by kakaraky** [comment]
Thanks for the quick reply. The re is supposed to traverse the input and display all matches, therefore default should not return -1, but just keep going. Here's the original re:
#include <assert.h>
#include <stdio.h>
#include <stdlib.h>

typedef unsigned char u8;

int lex(const u8 *start, const size_t size)
{
    const u8 *YYCURSOR = start;
    const u8 *YYLIMIT = start + size;
    const u8 *YYMARKER, *m, *yyt1;

    do { /*!re2c
        re2c:define:YYCTYPE = u8;
        re2c:define:YYFILL = "return 0;";
        re2c:flags:tags = 1;
    
        @m ([Bb][Ii][Gg])
        {
            printf("1@%08x\n", m - start);
            continue;
        }
    */
    } while (1);
}

int main(int argc, char* argv[])
{
    FILE *f;
    // read input file into buffer
    f = fopen(argv[1], "rb");
    fseek(f, 0, SEEK_END);
    const size_t fsize = (size_t) ftell(f);
    fseek(f, 0, SEEK_SET);
    u8 *buffer = (u8*) malloc(fsize + 1);
    fread(buffer, 1, fsize, f);
    buffer[fsize] = 0;
    fclose(f);

    lex(buffer, fsize);

    // cleanup
    free(buffer);
    return 0;
}

**Comment by kakaraky** [comment]
Oups, forgot to update the expression line with "@m **([^\x00]{16}"\n\x00\x00") |** ([Bb][Ii][Gg])" - please use that.

**Comment by kakaraky** [comment]
re2c retest.re >retest.c
cl -O2 retest.c
retest test
<test>:
  00000000:  6C 6B 66 6A-64 73 67 0A-00 00 0D 0A-64 66 67 73  lkfjdsg◙  ♪◙dfgs
  00000010:  66 67 0D 0A-62 49 67 67-75 73 2D 2D-             fg♪◙bIggus--

**Comment by skvadrik** [comment]
There are a few errors in the above code, in the decreasing level of severity:
- Default rule is not handled (if you run re2c with `-W` or specifically `-Wundefined-control-flow`, it would warn you, see [the explanation](https://re2c.org/manual/warnings/warnings.html)). This is a critical error, as there is no automatic default rule handling in re2c: if you don't specify the default action, it will be undefined (empty), and as a result all the code paths that end in default state (when none of the rules matches) will execute whatever code happens to be next, which may read from memory or jump to some unexpected state. If you need to skip characters that do not match any rules, it is fine, but you still need to handle the no-match case explicitly.

- The code does not handle EOF properly. There is a manual section about different [EOF handling mechanisms](https://re2c.org/manual/manual_c.html#eof-handling) in re2c, please read it to better understand the corrections I made (added EOF rule `$` and configuration `re2c:eof`).

- You need to use `re2c:api:style = free-form;` (or `re2c:define:YYFILL:naked = 1;` which was present before re2c-2.0) if you want to set `YYFILL` as free-form text rather than a function, see [the manual section about API styles](https://re2c.org/manual/manual_c.html#program-interface). Note that `YYFILL` form also differs depending on EOF-handling method. I corrected it to just `"0"` so that it always fails (in the generated code you can see that it is used in the context `if (0) ...`).

- The tag `@m` only applies to the left alternative: it does not apply to `[Bb][Ii][Gg]`, and it will be set to `NULL` if that alternative matches. I think this is a typo and you intended to apply `@m` to the whole rule (see my corrections below).

- If you use tags, it is recommended to use `/*!stags:re2c*/` directive to declare, initialize and manipulate the tag variables `yyt1` and so on, rather than manually declare them. I corrected the code, but this is not essential for the example to work. In fact if you only need a tag to mark the beginning of a token (and not in the middle of it), you can achieve the same effect by manually setting `m` to `YYCURSOR` at the beginning of the `while` loop.

Below is the corrected working example.

```c
#include <stdio.h>
#include <stdlib.h>

typedef unsigned char u8;

int lex(const u8 *start, const size_t size)
{
    const u8 *YYCURSOR = start;
    const u8 *YYLIMIT = start + size;
    const u8 *YYMARKER, *m;
    /*!stags:re2c format = "const u8 *@@;"; */

    do { /*!re2c
        re2c:define:YYCTYPE = u8;
        re2c:api:style      = free-form;
        re2c:define:YYFILL  = "0"; // YYFILL always fails
        re2c:eof            = 0;
        re2c:flags:tags     = 1;

        @m ([^\x00]{16}"\n\x00\x00" | [Bb][Ii][Gg])
        {
            printf("1@%08lx\n", m - start);
            continue;
        }
        $ { return 0; }
        * { continue; }
    */
    } while (1);
}

int main(int argc, char* argv[])
{
    FILE *f = fopen(argv[1], "rb");

    fseek(f, 0, SEEK_END);
    const size_t fsize = (size_t) ftell(f);
    fseek(f, 0, SEEK_SET);

    u8 *buffer = (u8*) malloc(fsize + 1);
    fread(buffer, 1, fsize, f);
    buffer[fsize] = 0;
    fclose(f);

    lex(buffer, fsize);

    free(buffer);
    return 0;
}
```

**Comment by kakaraky** [comment]
Thank you again for the prompt response and fixes, it does execute correctly now.

After working with so many res, I expected it by default to simply move on, which worked on 1 expression REs. Using ".*" did not work either, again without any errors or warnings, even though from a regex perspective it should have worked.

So default case handling is really mandatory and fails silently by default. This sounds like a problem, and while there is a way of doing things, does it make sense to align them with the regular regex expectations? In other words implement a continue default case or throw a compilation error?

If the answer is no, and I guess that would be the case for backwards compatibility, we can close the issue.

**Comment by skvadrik** [comment]
> After working with so many res, I expected it by default to simply move on

Re2c is a lexer generator, not a regexp library, and it has a bit different goals and challenges. It has a somewhat "do it yourself" attitude with regard to the interface code between the lexer and the input, which on one hand allows the users to cut off corners and gain full speed for their use cases, but on the other hand makes re2c more complex to use. This tradeoff is acceptable for some users, but surely not all.

> which worked on 1 expression REs

That was probably by accident. However, if you used warnings (`-W`), re2c would emit a very loud warning about that. Maybe it's time to enable `-Wundefined-control-flow` by default.

> Using ".*" did not work either, again without any errors or warnings

Here is the [summary of regular expression syntax](https://re2c.org/manual/manual_c.html#regular-expressions) in re2c. As you can see, strings in double quotes are literals. You can express "any symbol except newline any number of times" as `.*`, without the quotes. In this case `".*"` is a perfectly valid regexp that means "a dot followed by an asterisk", so re2c has no reason to warn.

> So default case handling is really mandatory and fails silently by default. This sounds like a problem, and while there is a way of doing things, does it make sense to align them with the regular regex expectations? In other words implement a continue default case or throw a compilation error?

The problem with "continue" is that it is not necessarily what the user wants or expects: there might be no outer loop to continue, or the loop may be a `goto`-loop with a custom loop header label, etc.

I think the best re2c can do to behave in a more intuitive way is to jump to a label at the end of the lexer block. I think this will be ok from the backwards compatibility standpoint (control flow will change only in the cases where it was already undefined). There is even a bug https://github.com/skvadrik/re2c/issues/143 about that. I will give it a bit more thought and probably just add a label at the end of the block.

> If the answer is no, and I guess that would be the case for backwards compatibility, we can close the issue.

Let's move this discussion to https://github.com/skvadrik/re2c/issues/143. This bug can be closed if everything else works for you. Thanks for raising the concern!

**Comment by kakaraky** [comment]
Thanks for the detailed reply, it makes a lot more sense now, and i sounds like the issue should be closed.

Just one details you may want to look into: the ".*" i mention earlier was used without quotes, like this:
`.* @m ([^\x00]{16}"\n\x00\x00" | [Bb][Ii][Gg])`

At least in my mind this expression should not need a default handler, however by removing `* { continue; }` it goes into an infinite loop.

**Comment by skvadrik** [comment]
> At least in my mind this expression should not need a default handler

@kakaraky It wouldn't work as you expect for a few reasons:
- `.` Excludes newline (it is equivalent to `[^\n]`), so there are inputs that contain `\n` that are not covered by `.*`.
- Even if you change `.*` to match-any `[^]*`, you'll find that this is greedy repetition, therefore if you have inputs with multiple words `big`, it will match only the last ocurrence (e.g. on `xbigybig` it will print offset 5 and skip offset 1 with the first `big`). That's because the lexer always tries to find the longest match, and the greedy component `[^]*` matches `big` as well.

However, looking closer at your example I realized that the code re2c generates in the case of all-consuming greedy repetition `[^]*` without default handler is not entirely correct. I'm working on a fix for this. This won't affect your example (it still should use a default handler instead of `.*`), but thanks for an interesting example that helped me find the bug.

**Comment by skvadrik** [comment]
@kakaraky In case you are interested, [here is a fix](https://github.com/skvadrik/re2c/commit/277f0295fc77a2dad3b9838e45f787319b54a25f) motivated by your comments. It does not change the fact that default rule `*` is needed in order to avoid undefined control flow in the lexer. The fix affects cases when the user chooses to have undefined control flow for some inputs (presumably because the invalid inputs never occur), and there is a loop through the initial state.

**Comment by kakaraky** [comment]
Thanks for that.
