### ISSUE TITLE
no goto

### ISSUE THREAD

**Issue by xR3b0rn** [skvadrik/re2c#384]
Removing `goto` from the code template, would make it possible to use the generated code in C++ `constexpr`-functions. I know the `goto`s are fundamental part of the concept of this library, however, it could be worth the effort in order to catch some C++ programmers which are looking for a compile-time regex library.

**Comment by skvadrik** [comment]
Closing, as `--loop-switch` is fully implemented and will soon be released.

**Comment by xR3b0rn** [comment]
Can you link the commit?

**Comment by skvadrik** [comment]
It's a bit difficult because the implementation for different features appeared in parts:
- added stubs: https://github.com/skvadrik/re2c/commit/e73b93f61fc3f754aa1317edcd54aeb403d050c8
- support for basic case: https://github.com/skvadrik/re2c/commit/c74080e656647bf321f614c14d9833db5a8c0b04
- support for conditions: https://github.com/skvadrik/re2c/commit/2d28bfea7977c82518ef97b0a90a49fa1d77e566
- support for storable state: https://github.com/skvadrik/re2c/commit/53259db5e7ab2ae08ebde54d652be12359778187

Generally, see https://github.com/skvadrik/re2c/search?q=loop%2Fswitch&type=commits

**Comment by xR3b0rn** [comment]
When you plan to integrate this feature in production?

**Comment by skvadrik** [comment]
It is already released in version 3.0: [release notes](https://re2c.org/releases/release_notes.html#release-3-0) and https://github.com/skvadrik/re2c/releases/tag/3.0
